### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by mhsamavatian** [jiawangbai/TA-LBF#2]
I got error for attack_one.py file. Should I replace labels_cuda instead of lables? 
File "attack_one.py", line 235, in <listcomp>    
 pa_acc = len([i for i in range(len(output)) if labels[i] == pred[i] and i != target_idx and i not in aux_idx]) / \   
File "...../anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 27, in wrapped    
 return f(*args, **kwargs) 
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by mhsamavatian** [comment]
Fixed with replacing labels_cuda. Just want to make sure it is correct?

**Comment by jiawangbai** [comment]
> Fixed with replacing labels_cuda. Just want to make sure it is correct?

Sure, it is correct. This error depends on the PyTorch version.
